site_name: RPID Project
site_url: https://rpidproject.github.io/rpid
repo_url: https://github.com/rpidproject/rpid
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- BiWeekly Meeting Agenda and Minutes:
  - '11-May-2017 Meeting': '11-May-2017.md'
  - '08-June-2017 Meeting': '08-June-2017.md'
  - '22-June-2017 Meeting': '22-June-2017.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors
