site_name: RPID Project
site_url: https://rpidproject.github.io/rpid
repo_url: https://github.com/rpidproject/rpid
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- BiWeekly Meeting Agenda and Minutes:
  - '17-August-2017': '17-August-2017.md'
  - '03-August-2017': '03-August-2017.md'
  - '20-July-2017': '20-July-2017.md'
  - '06-July-2017 Meeting': '06-July-2017.md'
  - '11-May-2017 Meeting': '11-May-2017.md'
  - '08-June-2017 Meeting': '08-June-2017.md'
  - '22-June-2017 Meeting': '22-June-2017.md'
- User Advisory Group:
  - 'Expectations': 'UAG-Expectations.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors
